<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '77baa94188df6367a1ce79c087ee7ca8',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/africhome?serverVersion=mariadb-10.4.24&charset=utf8mb4',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => 'ac536d3e44fd17c3de70339888a3c794',
  'MAILER_URL' => 'gmail://fullsecu22@gmail.com:Fullsecu123!@localhost',
);
