<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZOQ9kH5\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZOQ9kH5/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZOQ9kH5.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZOQ9kH5\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerZOQ9kH5\App_KernelProdContainer([
    'container.build_hash' => 'ZOQ9kH5',
    'container.build_id' => '490012c5',
    'container.build_time' => 1654148219,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZOQ9kH5');
