<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7w8xAiK\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7w8xAiK/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container7w8xAiK.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container7w8xAiK\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container7w8xAiK\App_KernelProdContainer([
    'container.build_hash' => '7w8xAiK',
    'container.build_id' => '0111b039',
    'container.build_time' => 1654101121,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7w8xAiK');
