<?php

namespace Container7w8xAiK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBatimentRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\BatimentRepository' shared autowired service.
     *
     * @return \App\Repository\BatimentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\BatimentRepository'] = new \App\Repository\BatimentRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
