<?php

namespace Container7w8xAiK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntiteControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\EntiteController' shared autowired service.
     *
     * @return \App\Controller\EntiteController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\EntiteController'] = $instance = new \App\Controller\EntiteController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\EntiteController', $container));

        return $instance;
    }
}
