<?php

namespace Container7w8xAiK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserPersisterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\DataPersister\UserPersister' shared autowired service.
     *
     * @return \App\DataPersister\UserPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\DataPersister\\UserPersister'] = new \App\DataPersister\UserPersister(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
