<?php

namespace ContainerJsc5MWV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bp5R2lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bp_5R2l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bp_5R2l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\EntiteController::blockEntite' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\EntiteController::getEntitesOfAdmin' => ['privates', '.service_locator.M9PMcRV', 'get_ServiceLocator_M9PMcRVService', true],
            'App\\Controller\\EntiteController::unblockEntite' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\UserCommonController::enterCodeConfirmation' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\UserCommonController::getEntitesAdmin' => ['privates', '.service_locator.M9PMcRV', 'get_ServiceLocator_M9PMcRVService', true],
            'App\\Controller\\UserCommonController::getUserById' => ['privates', '.service_locator.iTVYPJ2', 'get_ServiceLocator_ITVYPJ2Service', true],
            'App\\Controller\\UserCommonController::getUserInfos' => ['privates', '.service_locator.M9PMcRV', 'get_ServiceLocator_M9PMcRVService', true],
            'App\\Controller\\UserCommonController::requestPassword' => ['privates', '.service_locator._fOr.JJ', 'get_ServiceLocator_FOr_JJService', true],
            'App\\Controller\\UserCommonController::resetPassword' => ['privates', '.service_locator.hdrCzai', 'get_ServiceLocator_HdrCzaiService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\EntiteController:blockEntite' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\EntiteController:getEntitesOfAdmin' => ['privates', '.service_locator.M9PMcRV', 'get_ServiceLocator_M9PMcRVService', true],
            'App\\Controller\\EntiteController:unblockEntite' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\UserCommonController:enterCodeConfirmation' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\UserCommonController:getEntitesAdmin' => ['privates', '.service_locator.M9PMcRV', 'get_ServiceLocator_M9PMcRVService', true],
            'App\\Controller\\UserCommonController:getUserById' => ['privates', '.service_locator.iTVYPJ2', 'get_ServiceLocator_ITVYPJ2Service', true],
            'App\\Controller\\UserCommonController:getUserInfos' => ['privates', '.service_locator.M9PMcRV', 'get_ServiceLocator_M9PMcRVService', true],
            'App\\Controller\\UserCommonController:requestPassword' => ['privates', '.service_locator._fOr.JJ', 'get_ServiceLocator_FOr_JJService', true],
            'App\\Controller\\UserCommonController:resetPassword' => ['privates', '.service_locator.hdrCzai', 'get_ServiceLocator_HdrCzaiService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\EntiteController::blockEntite' => '?',
            'App\\Controller\\EntiteController::getEntitesOfAdmin' => '?',
            'App\\Controller\\EntiteController::unblockEntite' => '?',
            'App\\Controller\\UserCommonController::enterCodeConfirmation' => '?',
            'App\\Controller\\UserCommonController::getEntitesAdmin' => '?',
            'App\\Controller\\UserCommonController::getUserById' => '?',
            'App\\Controller\\UserCommonController::getUserInfos' => '?',
            'App\\Controller\\UserCommonController::requestPassword' => '?',
            'App\\Controller\\UserCommonController::resetPassword' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\EntiteController:blockEntite' => '?',
            'App\\Controller\\EntiteController:getEntitesOfAdmin' => '?',
            'App\\Controller\\EntiteController:unblockEntite' => '?',
            'App\\Controller\\UserCommonController:enterCodeConfirmation' => '?',
            'App\\Controller\\UserCommonController:getEntitesAdmin' => '?',
            'App\\Controller\\UserCommonController:getUserById' => '?',
            'App\\Controller\\UserCommonController:getUserInfos' => '?',
            'App\\Controller\\UserCommonController:requestPassword' => '?',
            'App\\Controller\\UserCommonController:resetPassword' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
