<?php

namespace ContainerZOQ9kH5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGestionnaireRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\GestionnaireRepository' shared autowired service.
     *
     * @return \App\Repository\GestionnaireRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\GestionnaireRepository'] = new \App\Repository\GestionnaireRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
