<?php

namespace ContainerZOQ9kH5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocalisationPersisterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\DataPersister\LocalisationPersister' shared autowired service.
     *
     * @return \App\DataPersister\LocalisationPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\DataPersister\\LocalisationPersister'] = new \App\DataPersister\LocalisationPersister(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['App\\Repository\\LocalisationRepository'] ?? $container->load('getLocalisationRepositoryService')), ($container->privates['App\\Repository\\TypeLocalisationRepository'] ?? $container->load('getTypeLocalisationRepositoryService')));
    }
}
