<?php

namespace ContainerZOQ9kH5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeLocalisationRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TypeLocalisationRepository' shared autowired service.
     *
     * @return \App\Repository\TypeLocalisationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TypeLocalisationRepository'] = new \App\Repository\TypeLocalisationRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
