<?php

namespace ContainerJO6zxzx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CQ8otlkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cQ8otlk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cQ8otlk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'requestStack' => ['services', 'request_stack', 'getRequestStackService', false],
            'taxeRepository' => ['privates', 'App\\Repository\\TaxeRepository', 'getTaxeRepositoryService', true],
        ], [
            'manager' => '?',
            'requestStack' => '?',
            'taxeRepository' => 'App\\Repository\\TaxeRepository',
        ]);
    }
}
