<?php

namespace ContainerXx3bvdd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9SlXs3lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9SlXs3l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9SlXs3l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'batimentCritereRepository' => ['privates', 'App\\Repository\\BatimentCritereRepository', 'getBatimentCritereRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'batimentCritereRepository' => 'App\\Repository\\BatimentCritereRepository',
            'manager' => '?',
        ]);
    }
}
