<?php

namespace ContainerQYHrB6q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployesControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\EmployesController' shared autowired service.
     *
     * @return \App\Controller\EmployesController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\EmployesController'] = $instance = new \App\Controller\EmployesController(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\EmployesController', $container));

        return $instance;
    }
}
