<?php

namespace ContainerQYHrB6q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParametrageControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ParametrageController' shared autowired service.
     *
     * @return \App\Controller\ParametrageController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ParametrageController'] = $instance = new \App\Controller\ParametrageController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\ParametrageController', $container));

        return $instance;
    }
}
