<?php

namespace ContainerQYHrB6q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParamTypesAgentsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ParamTypesAgentsRepository' shared autowired service.
     *
     * @return \App\Repository\ParamTypesAgentsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ParamTypesAgentsRepository'] = new \App\Repository\ParamTypesAgentsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
