<?php

namespace ContainerQYHrB6q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeEntityPersisterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\DataPersister\TypeEntityPersister' shared autowired service.
     *
     * @return \App\DataPersister\TypeEntityPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\DataPersister\\TypeEntityPersister'] = new \App\DataPersister\TypeEntityPersister(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
