<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMkxQMzG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMkxQMzG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMkxQMzG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMkxQMzG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMkxQMzG\App_KernelDevDebugContainer([
    'container.build_hash' => 'MkxQMzG',
    'container.build_id' => '41cbff5c',
    'container.build_time' => 1659020768,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMkxQMzG');
