<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container81qXeOx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container81qXeOx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container81qXeOx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container81qXeOx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container81qXeOx\App_KernelDevDebugContainer([
    'container.build_hash' => '81qXeOx',
    'container.build_id' => 'b77f145d',
    'container.build_time' => 1655479027,
], __DIR__.\DIRECTORY_SEPARATOR.'Container81qXeOx');
