<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BatimentOwner extends \App\Entity\BatimentOwner implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\BatimentOwner' . "\0" . 'id', '' . "\0" . 'App\\Entity\\BatimentOwner' . "\0" . 'proprietaires', '' . "\0" . 'App\\Entity\\BatimentOwner' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\BatimentOwner' . "\0" . 'dateAchat', '' . "\0" . 'App\\Entity\\BatimentOwner' . "\0" . 'dateVente', '' . "\0" . 'App\\Entity\\BatimentOwner' . "\0" . 'active', '' . "\0" . 'App\\Entity\\BatimentOwner' . "\0" . 'batiment'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\BatimentOwner' . "\0" . 'id', '' . "\0" . 'App\\Entity\\BatimentOwner' . "\0" . 'proprietaires', '' . "\0" . 'App\\Entity\\BatimentOwner' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\BatimentOwner' . "\0" . 'dateAchat', '' . "\0" . 'App\\Entity\\BatimentOwner' . "\0" . 'dateVente', '' . "\0" . 'App\\Entity\\BatimentOwner' . "\0" . 'active', '' . "\0" . 'App\\Entity\\BatimentOwner' . "\0" . 'batiment'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BatimentOwner $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getProprietaires(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProprietaires', []);

        return parent::getProprietaires();
    }

    /**
     * {@inheritDoc}
     */
    public function addProprietaire(\App\Entity\Proprietaire $proprietaire): \App\Entity\BatimentOwner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProprietaire', [$proprietaire]);

        return parent::addProprietaire($proprietaire);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProprietaire(\App\Entity\Proprietaire $proprietaire): \App\Entity\BatimentOwner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProprietaire', [$proprietaire]);

        return parent::removeProprietaire($proprietaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation(\DateTimeInterface $dateCreation): \App\Entity\BatimentOwner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAchat(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAchat', []);

        return parent::getDateAchat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAchat(?\DateTimeInterface $dateAchat): \App\Entity\BatimentOwner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAchat', [$dateAchat]);

        return parent::setDateAchat($dateAchat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateVente(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateVente', []);

        return parent::getDateVente();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateVente(?\DateTimeInterface $dateVente): \App\Entity\BatimentOwner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateVente', [$dateVente]);

        return parent::setDateVente($dateVente);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(bool $active): \App\Entity\BatimentOwner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getBatiment(): ?\App\Entity\Batiment
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBatiment', []);

        return parent::getBatiment();
    }

    /**
     * {@inheritDoc}
     */
    public function setBatiment(?\App\Entity\Batiment $batiment): \App\Entity\BatimentOwner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBatiment', [$batiment]);

        return parent::setBatiment($batiment);
    }

}
